# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
variables:
  solution: '**/*.sln'
  solutionName: 'Pokedex'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: 'PokedexAPI'

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildWebApi
    displayName: 'Check Web API Build'
    dependsOn: []
    jobs: 
      - template: check_build.yml
        parameters:
          solution: ${{variables.solution}}
          solutionName: ${{variables.solutionName}}
          buildPlatform: ${{variables.buildPlatform}}
          buildConfiguration: ${{variables.buildConfiguration}}
          projectName: ${{variables.projectName}}

  - stage: BuildWebApp
    displayName: 'Check Web App Build'
    dependsOn: []
    jobs: 
      - job: Publish 
        displayName: 'Build Angular App' 
        steps:
          - script: 
              npm install
              npm run build-prod

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifact' 
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/dist'
              ArtifactName: 'angular-app'
            
