variables:
  solution: '**/*.sln'
  solutionName: 'Pokedex'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  apiProjectName: 'PokedexAPI'
  appProjectName: 'PokedexApp'

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildPokedexWebApi
    displayName: 'Check Web API Build'
    dependsOn: []
    jobs: 
      - template: build_webapi.yml
        parameters:
          solution: ${{variables.solution}}
          solutionName: ${{variables.solutionName}}
          buildPlatform: ${{variables.buildPlatform}}
          buildConfiguration: ${{variables.buildConfiguration}}
          apiProjectName: ${{variables.apiProjectName}}

  - stage: BuildPokedexWebApp
    displayName: 'Check Web App Build'
    dependsOn: []
    jobs: 
      - template: build_webapp.yml
        parameters:
          appProjectName: ${{variables.appProjectName}}       

  - stage: Dev
    displayName: 'Deploy to Dev'
    #dependsOn: [BuildPokedexWebApi, BuildPokedexWebApp]
    jobs:
      - job: DeployInfrastructure
        variables:
          - group: PokedexDev
        displayName: 'Deploy Infrastructure'
        steps:
        - template: deploy_infrastructure.yml
          parameters:
           SpokeResourceGroupName: $(SpokeResourceGroupName)
           StorageAccountName: $(StorageAccountName)
           Environment: $(Environment)
      - job: DeployPokedexWebAPI
        pool: 'Azure Pipelines'
        displayName: 'Deploy Pokedex Web API'
        dependsOn: [DeployInfrastructure]
        steps:
          - template: deployment.yml
            parameters:
              serviceConnectionName: "Pokedex Service Connection"
              solutionName: ${{variables.solutionName}}
              ProjectName: ${{variables.apiProjectName}}
              appName: "pokedex-dev-web-api"
      - job: DeployPokedexWebApp
        pool: 'Azure Pipelines'
        displayName: 'Deploy Pokedex Web App'
        dependsOn: [DeployPokedexWebAPI]
        steps:
          - template: deployment.yml
            parameters:
              serviceConnectionName: "Pokedex Service Connection"
              solutionName: ${{variables.solutionName}}
              ProjectName: ${{variables.appProjectName}}
              appName: "pokedex-dev-web-app"


