# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Check Build'
    dependsOn: []
    jobs: 
      - job:
        steps:
        - template: check_build.yml
          parameters:
            solution: ${{variables.solution}}
            buildPlatform: ${{variables.buildPlatform}}
            buildConfiguration: ${{variables.buildConfiguration}}

