# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
variables:
  solution: '**/*.sln'
  solutionName: 'Pokedex'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  apiProjectName: 'PokedexAPI'
  appProjectName: 'PokedexApp'

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildWebApi
    displayName: 'Check Web API Build'
    dependsOn: []
    jobs: 
      - template: build_webapi.yml
        parameters:
          solution: ${{variables.solution}}
          solutionName: ${{variables.solutionName}}
          buildPlatform: ${{variables.buildPlatform}}
          buildConfiguration: ${{variables.buildConfiguration}}
          apiProjectName: ${{variables.apiProjectName}}

  - stage: BuildWebApp
    displayName: 'Check Web App Build'
    dependsOn: []
    jobs: 
      - template: build_webapp.yml
        parameters:
          appProjectName: ${{variables.appProjectName}}
            
  - stage: PublishArtifacts
    displayName: 'Publish Artifacts'
    dependsOn: [BuildWebApi, BuildWebApp]
    jobs:
      - job: 'Publish'
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'

  - stage: Dev
    displayName: 'Deploy to Dev'
    dependsOn: [PublishArtifacts]
    jobs:
      - job: DeployInfrastructur
        variables:
          - group: PokedexDev
        displayName: 'Deploy Infrastructure'
        steps:
        - template: deploy_infrastructure.yml
          parameters:
            Environment: $(Environment)