jobs:
  - job: Build 
    displayName: 'Build Angular App' 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd $(Build.SourcesDirectory)/${{parameters.appProjectName}}
        npm install
        npm run build --prod
      displayName: 'Build Angular App'

    - task: CopyFiles@2
      displayName: 'Copy Artifact to Staging Folder'
      inputs:
        SourceFolder: $(Build.SourcesDirectory)/${{parameters.appProjectName}}
        Contents: 'dist/**'
        TargetFolder: $(Build.ArtifactStagingDirectory)/${{parameters.appProjectName}}
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: false

    - task: ArchiveFiles@2
      displayName: 'Archive App Artifact'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/${{parameters.appProjectName}}'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/publish.zip'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Web App'
      inputs:
        ArtifactName: ${{parameters.appProjectName}}
        targetPath: '$(Build.ArtifactStagingDirectory)'