jobs:
  - job: Build
    displayName: 'Build and Publish API'
    steps:
      - task: UseDotNet@2
        displayName: "Use .NET 8.0.x SDK"
        inputs:
          packageType : sdk
          version: 8.0.x
          installationPath: $(Agent.ToolsDirectory)/dotnet
          workingDirectory: '$(Build.SourcesDirectory)/${{parameters.apiProjectName}}'

      - task: AzureKeyVault@2
        displayName: "Fetch secrets from Azure Key Vault"
        inputs:
          azureSubscription: ${{parameters.serviceConnectionName}} 
          KeyVaultName: 'pokedex-kv' 
          SecretsFilter: '*'

      - script: |
          echo "##vso[task.setvariable variable=DefaultConnection]$(DefaultConnection)"
          echo "##vso[task.setvariable variable=StorageAccountConnection]$(StorageAccountConnection)"
        displayName: 'Set environment variables from Key Vault'

#       - task: NuGetToolInstaller@1

      - script: dotnet restore ${{parameters.apiProjectName}}
        displayName: 'Nuget Restore'

      - script: dotnet build ${{parameters.apiProjectName}} --configuration ${{parameters.buildConfiguration}} --no-restore
        displayName: 'Build API'

      - script: dotnet test ${{parameters.apiProjectName}}.Tests
        displayName: 'Run Tests'

      - script: dotnet publish ${{parameters.apiProjectName}} --configuration Release --no-build --output ${{parameters.apiProjectName}}/publish
        displayName: 'Publish API'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '${{parameters.apiProjectName}}/publish'
          ArtifactName: ${{parameters.apiProjectName}}