jobs:
  - job: Build 
    displayName: 'Build Angular App' 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd $(Build.SourcesDirectory)/${{parameters.appProjectName}}
        npm install
        npm run build --prod
      displayName: 'Build Angular App'

    - task: CopyFiles@2
      displayName: 'Copy Artifact to Staging Folder'
      inputs:
        SourceFolder: $(Build.SourcesDirectory)/${{parameters.appProjectName}}/dist
        Contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)/${{parameters.appProjectName}}
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true