jobs:
  - job: Publish
    displayName: 'Build and Publish'
    steps:
      - task: UseDotNet@2
        displayName: "Use .NET 8.0.x SDK"
        inputs:
          version: 8.0.x
          installationPath: $(Agent.ToolsDirectory)/dotnet

      # - task: DotNetCoreCLI@2
      #   displayName: 'Nuget Restore'
      #   inputs: 
      #     commands: restore
      #     nugetConfigPath: $(Build.SourcesDirectory)/NuGet.config ##Check this is correct
      #     projects: $(Build.SourcesDirectory)/$(solutionName).sln
      #     feedsToUse: config

      # - task: DotNetCoreCLI@2
      #   displayName: 'Publish App'
      #   inputs:
      #     command: publish
      #     publishWebProjects: false
      #     arguments: '--configuration release'
      #     projects: '$(Build.SourcesDirectory)/${{parameters.SolutionName }}/${{ parameters.SolutionName}}.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: test
          projects: $(Build.SourcesDirectory)/${{parameters.SolutionName}}/${{parameters.SolutionName}}/${{parameters.SolutionName}}.Tests/${{parameters.SolutionName}}.Tests.csproj
          arguments: '--no-restore'

    # steps:
    # - task: NuGetToolInstaller@1

    # - task: NuGetCommand@2
    #   inputs:
    #     restoreSolution: '$(solution)'

    # - task: VSBuild@1
    #   inputs:
    #     solution: '$(solution)'
    #     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    #     platform: '$(buildPlatform)'
    #     configuration: '$(buildConfiguration)'

    # - task: VSTest@2
    #   inputs:
    #     platform: '$(buildPlatform)'
    #     configuration: '$(buildConfiguration)'