parameters:
  - name: solutionName
    type: string
  - name: ProjectName
    type: string
  - name: serviceConnectionName
    type: string
  - name: appName
    type: string

  # - job: Deploy
  #   dependsOn: Build
  #   pool:
  #     vmImage: 'windows-latest'

steps:
- task: DownloadBuildArtifacts@0
  displayName: 'Download App Package'
  inputs:
    buildType: 'current'
    artifactName: '${{parameters.ProjectName}}'
    downloadPath: ${{parameters.ProjectName}}/publish

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pokedex Service Connection' 
    appName: ${{parameters.appName}}
    package: ${{parameters.ProjectName}}/publish/**

# steps:
# - task: DownloadPipelineArtifact@2
#   displayName: 'Download App Package'
#   inputs:
#     artifact: '${{parameters.ProjectName}}'
#     path: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}'

# - task: ExtractFiles@1
#   inputs:
#     archiveFilePatterns: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}/publish.zip'
#     destinationFolder: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}/publish'

# # - task: ArchiveFiles@2
# #   inputs:
# #     rootFolderOrFile: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}/publish'
# #     includeRootFolder: false
# #     archiveType: 'zip'
# #     archiveFile: '$(Pipeline.Workspace)/${{parameters.ProjectName}}/publish.zip'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: ${{parameters.serviceConnectionName}}
#     appType: 'webApp'
#     appName: ${{parameters.appName}}
#     package: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}/publish'