parameters:
  - name: solutionName
    type: string
  - name: ProjectName
    type: string
  - name: serviceConnectionName
    type: string
  - name: appName
    type: string

steps:
- task: DownloadBuildArtifacts@0
  displayName: 'Download App Package'
  inputs:
    buildType: 'current'
    artifactName: '${{parameters.ProjectName}}'
    downloadPath: '$(Build.ArtifactStagingDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pokedex Service Connection' 
    appName: ${{parameters.appName}}
    package: '$(Build.ArtifactStagingDirectory)/${{parameters.ProjectName}}'