parameters:
  - name: solutionName
    type: string
  - name: ProjectName
    type: string
  - name: serviceConnectionName
    type: string
  - name: appName
    type: string

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download App Package'
  inputs:
    artifact: '${{parameters.ProjectName}}'
    path: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}'
    destinationFolder: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}/publish'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Pipeline.Workspace)/${{parameters.ProjectName}}/publish.zip'

- task: AzureWebApp@1
  inputs:
    azureSubscription: ${{parameters.serviceConnectionName}}
    appType: 'webApp'
    appName: ${{parameters.appName}}
    package: '$(Pipeline.Workspace)/artifacts/${{parameters.ProjectName}}/publish'